// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: change_password.proto

package com.graduate.design.proto;

public final class ChangePassword {
  private ChangePassword() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChangePasswordRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChangePasswordRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string oldHashId = 1;</code>
     * @return The oldHashId.
     */
    java.lang.String getOldHashId();
    /**
     * <code>string oldHashId = 1;</code>
     * @return The bytes for oldHashId.
     */
    com.google.protobuf.ByteString
        getOldHashIdBytes();

    /**
     * <code>string newHashId = 2;</code>
     * @return The newHashId.
     */
    java.lang.String getNewHashId();
    /**
     * <code>string newHashId = 2;</code>
     * @return The bytes for newHashId.
     */
    com.google.protobuf.ByteString
        getNewHashIdBytes();

    /**
     * <code>string key1 = 4;</code>
     * @return The key1.
     */
    java.lang.String getKey1();
    /**
     * <code>string key1 = 4;</code>
     * @return The bytes for key1.
     */
    com.google.protobuf.ByteString
        getKey1Bytes();

    /**
     * <code>string key2 = 5;</code>
     * @return The key2.
     */
    java.lang.String getKey2();
    /**
     * <code>string key2 = 5;</code>
     * @return The bytes for key2.
     */
    com.google.protobuf.ByteString
        getKey2Bytes();

    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    boolean hasBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    com.graduate.design.proto.Common.BaseReq getBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder();
  }
  /**
   * Protobuf type {@code ChangePasswordRequest}
   */
  public static final class ChangePasswordRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChangePasswordRequest)
      ChangePasswordRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChangePasswordRequest.newBuilder() to construct.
    private ChangePasswordRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChangePasswordRequest() {
      oldHashId_ = "";
      newHashId_ = "";
      key1_ = "";
      key2_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChangePasswordRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChangePasswordRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              oldHashId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              newHashId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              key1_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              key2_ = s;
              break;
            }
            case 2042: {
              com.graduate.design.proto.Common.BaseReq.Builder subBuilder = null;
              if (baseReq_ != null) {
                subBuilder = baseReq_.toBuilder();
              }
              baseReq_ = input.readMessage(com.graduate.design.proto.Common.BaseReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseReq_);
                baseReq_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.ChangePassword.ChangePasswordRequest.class, com.graduate.design.proto.ChangePassword.ChangePasswordRequest.Builder.class);
    }

    public static final int OLDHASHID_FIELD_NUMBER = 1;
    private volatile java.lang.Object oldHashId_;
    /**
     * <code>string oldHashId = 1;</code>
     * @return The oldHashId.
     */
    @java.lang.Override
    public java.lang.String getOldHashId() {
      java.lang.Object ref = oldHashId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldHashId_ = s;
        return s;
      }
    }
    /**
     * <code>string oldHashId = 1;</code>
     * @return The bytes for oldHashId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOldHashIdBytes() {
      java.lang.Object ref = oldHashId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldHashId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEWHASHID_FIELD_NUMBER = 2;
    private volatile java.lang.Object newHashId_;
    /**
     * <code>string newHashId = 2;</code>
     * @return The newHashId.
     */
    @java.lang.Override
    public java.lang.String getNewHashId() {
      java.lang.Object ref = newHashId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newHashId_ = s;
        return s;
      }
    }
    /**
     * <code>string newHashId = 2;</code>
     * @return The bytes for newHashId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNewHashIdBytes() {
      java.lang.Object ref = newHashId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newHashId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY1_FIELD_NUMBER = 4;
    private volatile java.lang.Object key1_;
    /**
     * <code>string key1 = 4;</code>
     * @return The key1.
     */
    @java.lang.Override
    public java.lang.String getKey1() {
      java.lang.Object ref = key1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key1_ = s;
        return s;
      }
    }
    /**
     * <code>string key1 = 4;</code>
     * @return The bytes for key1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKey1Bytes() {
      java.lang.Object ref = key1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY2_FIELD_NUMBER = 5;
    private volatile java.lang.Object key2_;
    /**
     * <code>string key2 = 5;</code>
     * @return The key2.
     */
    @java.lang.Override
    public java.lang.String getKey2() {
      java.lang.Object ref = key2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key2_ = s;
        return s;
      }
    }
    /**
     * <code>string key2 = 5;</code>
     * @return The bytes for key2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKey2Bytes() {
      java.lang.Object ref = key2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASEREQ_FIELD_NUMBER = 255;
    private com.graduate.design.proto.Common.BaseReq baseReq_;
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    @java.lang.Override
    public boolean hasBaseReq() {
      return baseReq_ != null;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseReq getBaseReq() {
      return baseReq_ == null ? com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder() {
      return getBaseReq();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oldHashId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oldHashId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newHashId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newHashId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key1_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, key1_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key2_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, key2_);
      }
      if (baseReq_ != null) {
        output.writeMessage(255, getBaseReq());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oldHashId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oldHashId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newHashId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newHashId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key1_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, key1_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key2_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, key2_);
      }
      if (baseReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseReq());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.ChangePassword.ChangePasswordRequest)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.ChangePassword.ChangePasswordRequest other = (com.graduate.design.proto.ChangePassword.ChangePasswordRequest) obj;

      if (!getOldHashId()
          .equals(other.getOldHashId())) return false;
      if (!getNewHashId()
          .equals(other.getNewHashId())) return false;
      if (!getKey1()
          .equals(other.getKey1())) return false;
      if (!getKey2()
          .equals(other.getKey2())) return false;
      if (hasBaseReq() != other.hasBaseReq()) return false;
      if (hasBaseReq()) {
        if (!getBaseReq()
            .equals(other.getBaseReq())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OLDHASHID_FIELD_NUMBER;
      hash = (53 * hash) + getOldHashId().hashCode();
      hash = (37 * hash) + NEWHASHID_FIELD_NUMBER;
      hash = (53 * hash) + getNewHashId().hashCode();
      hash = (37 * hash) + KEY1_FIELD_NUMBER;
      hash = (53 * hash) + getKey1().hashCode();
      hash = (37 * hash) + KEY2_FIELD_NUMBER;
      hash = (53 * hash) + getKey2().hashCode();
      if (hasBaseReq()) {
        hash = (37 * hash) + BASEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getBaseReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.ChangePassword.ChangePasswordRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChangePasswordRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChangePasswordRequest)
        com.graduate.design.proto.ChangePassword.ChangePasswordRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.ChangePassword.ChangePasswordRequest.class, com.graduate.design.proto.ChangePassword.ChangePasswordRequest.Builder.class);
      }

      // Construct using com.graduate.design.proto.ChangePassword.ChangePasswordRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        oldHashId_ = "";

        newHashId_ = "";

        key1_ = "";

        key2_ = "";

        if (baseReqBuilder_ == null) {
          baseReq_ = null;
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordRequest_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.ChangePassword.ChangePasswordRequest getDefaultInstanceForType() {
        return com.graduate.design.proto.ChangePassword.ChangePasswordRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.ChangePassword.ChangePasswordRequest build() {
        com.graduate.design.proto.ChangePassword.ChangePasswordRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.ChangePassword.ChangePasswordRequest buildPartial() {
        com.graduate.design.proto.ChangePassword.ChangePasswordRequest result = new com.graduate.design.proto.ChangePassword.ChangePasswordRequest(this);
        result.oldHashId_ = oldHashId_;
        result.newHashId_ = newHashId_;
        result.key1_ = key1_;
        result.key2_ = key2_;
        if (baseReqBuilder_ == null) {
          result.baseReq_ = baseReq_;
        } else {
          result.baseReq_ = baseReqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.ChangePassword.ChangePasswordRequest) {
          return mergeFrom((com.graduate.design.proto.ChangePassword.ChangePasswordRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.ChangePassword.ChangePasswordRequest other) {
        if (other == com.graduate.design.proto.ChangePassword.ChangePasswordRequest.getDefaultInstance()) return this;
        if (!other.getOldHashId().isEmpty()) {
          oldHashId_ = other.oldHashId_;
          onChanged();
        }
        if (!other.getNewHashId().isEmpty()) {
          newHashId_ = other.newHashId_;
          onChanged();
        }
        if (!other.getKey1().isEmpty()) {
          key1_ = other.key1_;
          onChanged();
        }
        if (!other.getKey2().isEmpty()) {
          key2_ = other.key2_;
          onChanged();
        }
        if (other.hasBaseReq()) {
          mergeBaseReq(other.getBaseReq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.ChangePassword.ChangePasswordRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.ChangePassword.ChangePasswordRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object oldHashId_ = "";
      /**
       * <code>string oldHashId = 1;</code>
       * @return The oldHashId.
       */
      public java.lang.String getOldHashId() {
        java.lang.Object ref = oldHashId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oldHashId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string oldHashId = 1;</code>
       * @return The bytes for oldHashId.
       */
      public com.google.protobuf.ByteString
          getOldHashIdBytes() {
        java.lang.Object ref = oldHashId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldHashId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string oldHashId = 1;</code>
       * @param value The oldHashId to set.
       * @return This builder for chaining.
       */
      public Builder setOldHashId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oldHashId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string oldHashId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldHashId() {
        
        oldHashId_ = getDefaultInstance().getOldHashId();
        onChanged();
        return this;
      }
      /**
       * <code>string oldHashId = 1;</code>
       * @param value The bytes for oldHashId to set.
       * @return This builder for chaining.
       */
      public Builder setOldHashIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oldHashId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object newHashId_ = "";
      /**
       * <code>string newHashId = 2;</code>
       * @return The newHashId.
       */
      public java.lang.String getNewHashId() {
        java.lang.Object ref = newHashId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          newHashId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string newHashId = 2;</code>
       * @return The bytes for newHashId.
       */
      public com.google.protobuf.ByteString
          getNewHashIdBytes() {
        java.lang.Object ref = newHashId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newHashId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string newHashId = 2;</code>
       * @param value The newHashId to set.
       * @return This builder for chaining.
       */
      public Builder setNewHashId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        newHashId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string newHashId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewHashId() {
        
        newHashId_ = getDefaultInstance().getNewHashId();
        onChanged();
        return this;
      }
      /**
       * <code>string newHashId = 2;</code>
       * @param value The bytes for newHashId to set.
       * @return This builder for chaining.
       */
      public Builder setNewHashIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        newHashId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key1_ = "";
      /**
       * <code>string key1 = 4;</code>
       * @return The key1.
       */
      public java.lang.String getKey1() {
        java.lang.Object ref = key1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key1 = 4;</code>
       * @return The bytes for key1.
       */
      public com.google.protobuf.ByteString
          getKey1Bytes() {
        java.lang.Object ref = key1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key1 = 4;</code>
       * @param value The key1 to set.
       * @return This builder for chaining.
       */
      public Builder setKey1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey1() {
        
        key1_ = getDefaultInstance().getKey1();
        onChanged();
        return this;
      }
      /**
       * <code>string key1 = 4;</code>
       * @param value The bytes for key1 to set.
       * @return This builder for chaining.
       */
      public Builder setKey1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key2_ = "";
      /**
       * <code>string key2 = 5;</code>
       * @return The key2.
       */
      public java.lang.String getKey2() {
        java.lang.Object ref = key2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key2 = 5;</code>
       * @return The bytes for key2.
       */
      public com.google.protobuf.ByteString
          getKey2Bytes() {
        java.lang.Object ref = key2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key2 = 5;</code>
       * @param value The key2 to set.
       * @return This builder for chaining.
       */
      public Builder setKey2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key2 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey2() {
        
        key2_ = getDefaultInstance().getKey2();
        onChanged();
        return this;
      }
      /**
       * <code>string key2 = 5;</code>
       * @param value The bytes for key2 to set.
       * @return This builder for chaining.
       */
      public Builder setKey2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key2_ = value;
        onChanged();
        return this;
      }

      private com.graduate.design.proto.Common.BaseReq baseReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder> baseReqBuilder_;
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return Whether the baseReq field is set.
       */
      public boolean hasBaseReq() {
        return baseReqBuilder_ != null || baseReq_ != null;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return The baseReq.
       */
      public com.graduate.design.proto.Common.BaseReq getBaseReq() {
        if (baseReqBuilder_ == null) {
          return baseReq_ == null ? com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
        } else {
          return baseReqBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(com.graduate.design.proto.Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseReq_ = value;
          onChanged();
        } else {
          baseReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(
          com.graduate.design.proto.Common.BaseReq.Builder builderForValue) {
        if (baseReqBuilder_ == null) {
          baseReq_ = builderForValue.build();
          onChanged();
        } else {
          baseReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder mergeBaseReq(com.graduate.design.proto.Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (baseReq_ != null) {
            baseReq_ =
              com.graduate.design.proto.Common.BaseReq.newBuilder(baseReq_).mergeFrom(value).buildPartial();
          } else {
            baseReq_ = value;
          }
          onChanged();
        } else {
          baseReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder clearBaseReq() {
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
          onChanged();
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseReq.Builder getBaseReqBuilder() {
        
        onChanged();
        return getBaseReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder() {
        if (baseReqBuilder_ != null) {
          return baseReqBuilder_.getMessageOrBuilder();
        } else {
          return baseReq_ == null ?
              com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder> 
          getBaseReqFieldBuilder() {
        if (baseReqBuilder_ == null) {
          baseReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder>(
                  getBaseReq(),
                  getParentForChildren(),
                  isClean());
          baseReq_ = null;
        }
        return baseReqBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChangePasswordRequest)
    }

    // @@protoc_insertion_point(class_scope:ChangePasswordRequest)
    private static final com.graduate.design.proto.ChangePassword.ChangePasswordRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.ChangePassword.ChangePasswordRequest();
    }

    public static com.graduate.design.proto.ChangePassword.ChangePasswordRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChangePasswordRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChangePasswordRequest>() {
      @java.lang.Override
      public ChangePasswordRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangePasswordRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChangePasswordRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChangePasswordRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.ChangePassword.ChangePasswordRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChangePasswordResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChangePasswordResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    boolean hasBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    com.graduate.design.proto.Common.BaseResp getBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder();
  }
  /**
   * Protobuf type {@code ChangePasswordResponse}
   */
  public static final class ChangePasswordResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChangePasswordResponse)
      ChangePasswordResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChangePasswordResponse.newBuilder() to construct.
    private ChangePasswordResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChangePasswordResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChangePasswordResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChangePasswordResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 2042: {
              com.graduate.design.proto.Common.BaseResp.Builder subBuilder = null;
              if (baseResp_ != null) {
                subBuilder = baseResp_.toBuilder();
              }
              baseResp_ = input.readMessage(com.graduate.design.proto.Common.BaseResp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResp_);
                baseResp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.ChangePassword.ChangePasswordResponse.class, com.graduate.design.proto.ChangePassword.ChangePasswordResponse.Builder.class);
    }

    public static final int BASERESP_FIELD_NUMBER = 255;
    private com.graduate.design.proto.Common.BaseResp baseResp_;
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    @java.lang.Override
    public boolean hasBaseResp() {
      return baseResp_ != null;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseResp getBaseResp() {
      return baseResp_ == null ? com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder() {
      return getBaseResp();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseResp_ != null) {
        output.writeMessage(255, getBaseResp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseResp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.ChangePassword.ChangePasswordResponse)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.ChangePassword.ChangePasswordResponse other = (com.graduate.design.proto.ChangePassword.ChangePasswordResponse) obj;

      if (hasBaseResp() != other.hasBaseResp()) return false;
      if (hasBaseResp()) {
        if (!getBaseResp()
            .equals(other.getBaseResp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseResp()) {
        hash = (37 * hash) + BASERESP_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.ChangePassword.ChangePasswordResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChangePasswordResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChangePasswordResponse)
        com.graduate.design.proto.ChangePassword.ChangePasswordResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.ChangePassword.ChangePasswordResponse.class, com.graduate.design.proto.ChangePassword.ChangePasswordResponse.Builder.class);
      }

      // Construct using com.graduate.design.proto.ChangePassword.ChangePasswordResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.ChangePassword.internal_static_ChangePasswordResponse_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.ChangePassword.ChangePasswordResponse getDefaultInstanceForType() {
        return com.graduate.design.proto.ChangePassword.ChangePasswordResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.ChangePassword.ChangePasswordResponse build() {
        com.graduate.design.proto.ChangePassword.ChangePasswordResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.ChangePassword.ChangePasswordResponse buildPartial() {
        com.graduate.design.proto.ChangePassword.ChangePasswordResponse result = new com.graduate.design.proto.ChangePassword.ChangePasswordResponse(this);
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.ChangePassword.ChangePasswordResponse) {
          return mergeFrom((com.graduate.design.proto.ChangePassword.ChangePasswordResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.ChangePassword.ChangePasswordResponse other) {
        if (other == com.graduate.design.proto.ChangePassword.ChangePasswordResponse.getDefaultInstance()) return this;
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.ChangePassword.ChangePasswordResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.ChangePassword.ChangePasswordResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.graduate.design.proto.Common.BaseResp baseResp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder> baseRespBuilder_;
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return Whether the baseResp field is set.
       */
      public boolean hasBaseResp() {
        return baseRespBuilder_ != null || baseResp_ != null;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return The baseResp.
       */
      public com.graduate.design.proto.Common.BaseResp getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_ == null ? com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(com.graduate.design.proto.Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(
          com.graduate.design.proto.Common.BaseResp.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder mergeBaseResp(com.graduate.design.proto.Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (baseResp_ != null) {
            baseResp_ =
              com.graduate.design.proto.Common.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
          onChanged();
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseResp.Builder getBaseRespBuilder() {
        
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_ == null ?
              com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder> 
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder>(
                  getBaseResp(),
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChangePasswordResponse)
    }

    // @@protoc_insertion_point(class_scope:ChangePasswordResponse)
    private static final com.graduate.design.proto.ChangePassword.ChangePasswordResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.ChangePassword.ChangePasswordResponse();
    }

    public static com.graduate.design.proto.ChangePassword.ChangePasswordResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChangePasswordResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChangePasswordResponse>() {
      @java.lang.Override
      public ChangePasswordResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangePasswordResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChangePasswordResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChangePasswordResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.ChangePassword.ChangePasswordResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangePasswordRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangePasswordRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangePasswordResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangePasswordResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025change_password.proto\032\014common.proto\"u\n" +
      "\025ChangePasswordRequest\022\021\n\toldHashId\030\001 \001(" +
      "\t\022\021\n\tnewHashId\030\002 \001(\t\022\014\n\004key1\030\004 \001(\t\022\014\n\004ke" +
      "y2\030\005 \001(\t\022\032\n\007baseReq\030\377\001 \001(\0132\010.BaseReq\"6\n\026" +
      "ChangePasswordResponse\022\034\n\010baseResp\030\377\001 \001(" +
      "\0132\t.BaseRespBS\n\031com.graduate.design.prot" +
      "oB\016ChangePasswordZ&github.com/JackTJC/gm" +
      "FS_backend/pb_genb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.graduate.design.proto.Common.getDescriptor(),
        });
    internal_static_ChangePasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChangePasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangePasswordRequest_descriptor,
        new java.lang.String[] { "OldHashId", "NewHashId", "Key1", "Key2", "BaseReq", });
    internal_static_ChangePasswordResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChangePasswordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangePasswordResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    com.graduate.design.proto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
