// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_dir.proto

package com.graduate.design.proto;

public final class GetDir {
  private GetDir() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetDirRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetDirRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * dir节点id
     * </pre>
     *
     * <code>int64 nodeId = 1;</code>
     * @return The nodeId.
     */
    long getNodeId();

    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    boolean hasBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    com.graduate.design.proto.Common.BaseReq getBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder();
  }
  /**
   * Protobuf type {@code GetDirRequest}
   */
  public static final class GetDirRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetDirRequest)
      GetDirRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetDirRequest.newBuilder() to construct.
    private GetDirRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetDirRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetDirRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetDirRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nodeId_ = input.readInt64();
              break;
            }
            case 2042: {
              com.graduate.design.proto.Common.BaseReq.Builder subBuilder = null;
              if (baseReq_ != null) {
                subBuilder = baseReq_.toBuilder();
              }
              baseReq_ = input.readMessage(com.graduate.design.proto.Common.BaseReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseReq_);
                baseReq_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.GetDir.internal_static_GetDirRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.GetDir.internal_static_GetDirRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.GetDir.GetDirRequest.class, com.graduate.design.proto.GetDir.GetDirRequest.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    private long nodeId_;
    /**
     * <pre>
     * dir节点id
     * </pre>
     *
     * <code>int64 nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public long getNodeId() {
      return nodeId_;
    }

    public static final int BASEREQ_FIELD_NUMBER = 255;
    private com.graduate.design.proto.Common.BaseReq baseReq_;
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    @java.lang.Override
    public boolean hasBaseReq() {
      return baseReq_ != null;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseReq getBaseReq() {
      return baseReq_ == null ? com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder() {
      return getBaseReq();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeId_ != 0L) {
        output.writeInt64(1, nodeId_);
      }
      if (baseReq_ != null) {
        output.writeMessage(255, getBaseReq());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nodeId_);
      }
      if (baseReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseReq());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.GetDir.GetDirRequest)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.GetDir.GetDirRequest other = (com.graduate.design.proto.GetDir.GetDirRequest) obj;

      if (getNodeId()
          != other.getNodeId()) return false;
      if (hasBaseReq() != other.hasBaseReq()) return false;
      if (hasBaseReq()) {
        if (!getBaseReq()
            .equals(other.getBaseReq())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNodeId());
      if (hasBaseReq()) {
        hash = (37 * hash) + BASEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getBaseReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetDir.GetDirRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.GetDir.GetDirRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetDirRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetDirRequest)
        com.graduate.design.proto.GetDir.GetDirRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.GetDir.internal_static_GetDirRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.GetDir.internal_static_GetDirRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.GetDir.GetDirRequest.class, com.graduate.design.proto.GetDir.GetDirRequest.Builder.class);
      }

      // Construct using com.graduate.design.proto.GetDir.GetDirRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeId_ = 0L;

        if (baseReqBuilder_ == null) {
          baseReq_ = null;
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.GetDir.internal_static_GetDirRequest_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetDir.GetDirRequest getDefaultInstanceForType() {
        return com.graduate.design.proto.GetDir.GetDirRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.GetDir.GetDirRequest build() {
        com.graduate.design.proto.GetDir.GetDirRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetDir.GetDirRequest buildPartial() {
        com.graduate.design.proto.GetDir.GetDirRequest result = new com.graduate.design.proto.GetDir.GetDirRequest(this);
        result.nodeId_ = nodeId_;
        if (baseReqBuilder_ == null) {
          result.baseReq_ = baseReq_;
        } else {
          result.baseReq_ = baseReqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.GetDir.GetDirRequest) {
          return mergeFrom((com.graduate.design.proto.GetDir.GetDirRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.GetDir.GetDirRequest other) {
        if (other == com.graduate.design.proto.GetDir.GetDirRequest.getDefaultInstance()) return this;
        if (other.getNodeId() != 0L) {
          setNodeId(other.getNodeId());
        }
        if (other.hasBaseReq()) {
          mergeBaseReq(other.getBaseReq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.GetDir.GetDirRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.GetDir.GetDirRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long nodeId_ ;
      /**
       * <pre>
       * dir节点id
       * </pre>
       *
       * <code>int64 nodeId = 1;</code>
       * @return The nodeId.
       */
      @java.lang.Override
      public long getNodeId() {
        return nodeId_;
      }
      /**
       * <pre>
       * dir节点id
       * </pre>
       *
       * <code>int64 nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(long value) {
        
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dir节点id
       * </pre>
       *
       * <code>int64 nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        
        nodeId_ = 0L;
        onChanged();
        return this;
      }

      private com.graduate.design.proto.Common.BaseReq baseReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder> baseReqBuilder_;
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return Whether the baseReq field is set.
       */
      public boolean hasBaseReq() {
        return baseReqBuilder_ != null || baseReq_ != null;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return The baseReq.
       */
      public com.graduate.design.proto.Common.BaseReq getBaseReq() {
        if (baseReqBuilder_ == null) {
          return baseReq_ == null ? com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
        } else {
          return baseReqBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(com.graduate.design.proto.Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseReq_ = value;
          onChanged();
        } else {
          baseReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(
          com.graduate.design.proto.Common.BaseReq.Builder builderForValue) {
        if (baseReqBuilder_ == null) {
          baseReq_ = builderForValue.build();
          onChanged();
        } else {
          baseReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder mergeBaseReq(com.graduate.design.proto.Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (baseReq_ != null) {
            baseReq_ =
              com.graduate.design.proto.Common.BaseReq.newBuilder(baseReq_).mergeFrom(value).buildPartial();
          } else {
            baseReq_ = value;
          }
          onChanged();
        } else {
          baseReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder clearBaseReq() {
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
          onChanged();
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseReq.Builder getBaseReqBuilder() {
        
        onChanged();
        return getBaseReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder() {
        if (baseReqBuilder_ != null) {
          return baseReqBuilder_.getMessageOrBuilder();
        } else {
          return baseReq_ == null ?
              com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder> 
          getBaseReqFieldBuilder() {
        if (baseReqBuilder_ == null) {
          baseReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder>(
                  getBaseReq(),
                  getParentForChildren(),
                  isClean());
          baseReq_ = null;
        }
        return baseReqBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetDirRequest)
    }

    // @@protoc_insertion_point(class_scope:GetDirRequest)
    private static final com.graduate.design.proto.GetDir.GetDirRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.GetDir.GetDirRequest();
    }

    public static com.graduate.design.proto.GetDir.GetDirRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDirRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetDirRequest>() {
      @java.lang.Override
      public GetDirRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetDirRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetDirRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetDirRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.GetDir.GetDirRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetDirResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetDirResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 节点id列表
     * </pre>
     *
     * <code>repeated int64 nodeIdList = 1;</code>
     * @return A list containing the nodeIdList.
     */
    java.util.List<java.lang.Long> getNodeIdListList();
    /**
     * <pre>
     * 节点id列表
     * </pre>
     *
     * <code>repeated int64 nodeIdList = 1;</code>
     * @return The count of nodeIdList.
     */
    int getNodeIdListCount();
    /**
     * <pre>
     * 节点id列表
     * </pre>
     *
     * <code>repeated int64 nodeIdList = 1;</code>
     * @param index The index of the element to return.
     * @return The nodeIdList at the given index.
     */
    long getNodeIdList(int index);

    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    boolean hasBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    com.graduate.design.proto.Common.BaseResp getBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder();
  }
  /**
   * Protobuf type {@code GetDirResponse}
   */
  public static final class GetDirResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetDirResponse)
      GetDirResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetDirResponse.newBuilder() to construct.
    private GetDirResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetDirResponse() {
      nodeIdList_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetDirResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetDirResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodeIdList_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeIdList_.addLong(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                nodeIdList_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                nodeIdList_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 2042: {
              com.graduate.design.proto.Common.BaseResp.Builder subBuilder = null;
              if (baseResp_ != null) {
                subBuilder = baseResp_.toBuilder();
              }
              baseResp_ = input.readMessage(com.graduate.design.proto.Common.BaseResp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResp_);
                baseResp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodeIdList_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.GetDir.internal_static_GetDirResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.GetDir.internal_static_GetDirResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.GetDir.GetDirResponse.class, com.graduate.design.proto.GetDir.GetDirResponse.Builder.class);
    }

    public static final int NODEIDLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.LongList nodeIdList_;
    /**
     * <pre>
     * 节点id列表
     * </pre>
     *
     * <code>repeated int64 nodeIdList = 1;</code>
     * @return A list containing the nodeIdList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getNodeIdListList() {
      return nodeIdList_;
    }
    /**
     * <pre>
     * 节点id列表
     * </pre>
     *
     * <code>repeated int64 nodeIdList = 1;</code>
     * @return The count of nodeIdList.
     */
    public int getNodeIdListCount() {
      return nodeIdList_.size();
    }
    /**
     * <pre>
     * 节点id列表
     * </pre>
     *
     * <code>repeated int64 nodeIdList = 1;</code>
     * @param index The index of the element to return.
     * @return The nodeIdList at the given index.
     */
    public long getNodeIdList(int index) {
      return nodeIdList_.getLong(index);
    }
    private int nodeIdListMemoizedSerializedSize = -1;

    public static final int BASERESP_FIELD_NUMBER = 255;
    private com.graduate.design.proto.Common.BaseResp baseResp_;
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    @java.lang.Override
    public boolean hasBaseResp() {
      return baseResp_ != null;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseResp getBaseResp() {
      return baseResp_ == null ? com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder() {
      return getBaseResp();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNodeIdListList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(nodeIdListMemoizedSerializedSize);
      }
      for (int i = 0; i < nodeIdList_.size(); i++) {
        output.writeInt64NoTag(nodeIdList_.getLong(i));
      }
      if (baseResp_ != null) {
        output.writeMessage(255, getBaseResp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < nodeIdList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(nodeIdList_.getLong(i));
        }
        size += dataSize;
        if (!getNodeIdListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        nodeIdListMemoizedSerializedSize = dataSize;
      }
      if (baseResp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.GetDir.GetDirResponse)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.GetDir.GetDirResponse other = (com.graduate.design.proto.GetDir.GetDirResponse) obj;

      if (!getNodeIdListList()
          .equals(other.getNodeIdListList())) return false;
      if (hasBaseResp() != other.hasBaseResp()) return false;
      if (hasBaseResp()) {
        if (!getBaseResp()
            .equals(other.getBaseResp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeIdListCount() > 0) {
        hash = (37 * hash) + NODEIDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getNodeIdListList().hashCode();
      }
      if (hasBaseResp()) {
        hash = (37 * hash) + BASERESP_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetDir.GetDirResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.GetDir.GetDirResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetDirResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetDirResponse)
        com.graduate.design.proto.GetDir.GetDirResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.GetDir.internal_static_GetDirResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.GetDir.internal_static_GetDirResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.GetDir.GetDirResponse.class, com.graduate.design.proto.GetDir.GetDirResponse.Builder.class);
      }

      // Construct using com.graduate.design.proto.GetDir.GetDirResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeIdList_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.GetDir.internal_static_GetDirResponse_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetDir.GetDirResponse getDefaultInstanceForType() {
        return com.graduate.design.proto.GetDir.GetDirResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.GetDir.GetDirResponse build() {
        com.graduate.design.proto.GetDir.GetDirResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetDir.GetDirResponse buildPartial() {
        com.graduate.design.proto.GetDir.GetDirResponse result = new com.graduate.design.proto.GetDir.GetDirResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          nodeIdList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nodeIdList_ = nodeIdList_;
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.GetDir.GetDirResponse) {
          return mergeFrom((com.graduate.design.proto.GetDir.GetDirResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.GetDir.GetDirResponse other) {
        if (other == com.graduate.design.proto.GetDir.GetDirResponse.getDefaultInstance()) return this;
        if (!other.nodeIdList_.isEmpty()) {
          if (nodeIdList_.isEmpty()) {
            nodeIdList_ = other.nodeIdList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodeIdListIsMutable();
            nodeIdList_.addAll(other.nodeIdList_);
          }
          onChanged();
        }
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.GetDir.GetDirResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.GetDir.GetDirResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList nodeIdList_ = emptyLongList();
      private void ensureNodeIdListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodeIdList_ = mutableCopy(nodeIdList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @return A list containing the nodeIdList.
       */
      public java.util.List<java.lang.Long>
          getNodeIdListList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(nodeIdList_) : nodeIdList_;
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @return The count of nodeIdList.
       */
      public int getNodeIdListCount() {
        return nodeIdList_.size();
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @param index The index of the element to return.
       * @return The nodeIdList at the given index.
       */
      public long getNodeIdList(int index) {
        return nodeIdList_.getLong(index);
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @param index The index to set the value at.
       * @param value The nodeIdList to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdList(
          int index, long value) {
        ensureNodeIdListIsMutable();
        nodeIdList_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @param value The nodeIdList to add.
       * @return This builder for chaining.
       */
      public Builder addNodeIdList(long value) {
        ensureNodeIdListIsMutable();
        nodeIdList_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @param values The nodeIdList to add.
       * @return This builder for chaining.
       */
      public Builder addAllNodeIdList(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureNodeIdListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodeIdList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点id列表
       * </pre>
       *
       * <code>repeated int64 nodeIdList = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeIdList() {
        nodeIdList_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.graduate.design.proto.Common.BaseResp baseResp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder> baseRespBuilder_;
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return Whether the baseResp field is set.
       */
      public boolean hasBaseResp() {
        return baseRespBuilder_ != null || baseResp_ != null;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return The baseResp.
       */
      public com.graduate.design.proto.Common.BaseResp getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_ == null ? com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(com.graduate.design.proto.Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(
          com.graduate.design.proto.Common.BaseResp.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder mergeBaseResp(com.graduate.design.proto.Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (baseResp_ != null) {
            baseResp_ =
              com.graduate.design.proto.Common.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
          onChanged();
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseResp.Builder getBaseRespBuilder() {
        
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_ == null ?
              com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder> 
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder>(
                  getBaseResp(),
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetDirResponse)
    }

    // @@protoc_insertion_point(class_scope:GetDirResponse)
    private static final com.graduate.design.proto.GetDir.GetDirResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.GetDir.GetDirResponse();
    }

    public static com.graduate.design.proto.GetDir.GetDirResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDirResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetDirResponse>() {
      @java.lang.Override
      public GetDirResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetDirResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetDirResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetDirResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.GetDir.GetDirResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDirRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDirRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDirResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDirResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rget_dir.proto\032\014common.proto\";\n\rGetDirR" +
      "equest\022\016\n\006nodeId\030\001 \001(\003\022\032\n\007baseReq\030\377\001 \001(\013" +
      "2\010.BaseReq\"B\n\016GetDirResponse\022\022\n\nnodeIdLi" +
      "st\030\001 \003(\003\022\034\n\010baseResp\030\377\001 \001(\0132\t.BaseRespB-" +
      "\n\031com.graduate.design.protoB\006GetDirZ\010./p" +
      "b_genb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.graduate.design.proto.Common.getDescriptor(),
        });
    internal_static_GetDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDirRequest_descriptor,
        new java.lang.String[] { "NodeId", "BaseReq", });
    internal_static_GetDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDirResponse_descriptor,
        new java.lang.String[] { "NodeIdList", "BaseResp", });
    com.graduate.design.proto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
