// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_node.proto

package com.graduate.design.proto;

public final class GetNode {
  private GetNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetNodeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetNodeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>     * 节点id
     * </pre>
     *
     * <code>int64 nodeId = 1;</code>
     * @return The nodeId.
     */
    long getNodeId();

    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    boolean hasBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    Common.BaseReq getBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    Common.BaseReqOrBuilder getBaseReqOrBuilder();
  }
  /**
   * Protobuf type {@code GetNodeRequest}
   */
  public static final class GetNodeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetNodeRequest)
      GetNodeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetNodeRequest.newBuilder() to construct.
    private GetNodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetNodeRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetNodeRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetNodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nodeId_ = input.readInt64();
              break;
            }
            case 2042: {
              Common.BaseReq.Builder subBuilder = null;
              if (baseReq_ != null) {
                subBuilder = baseReq_.toBuilder();
              }
              baseReq_ = input.readMessage(Common.BaseReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseReq_);
                baseReq_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetNode.internal_static_GetNodeRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetNode.internal_static_GetNodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetNodeRequest.class, Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    private long nodeId_;
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>int64 nodeId = 1;</code>
     * @return The nodeId.
     */
    @Override
    public long getNodeId() {
      return nodeId_;
    }

    public static final int BASEREQ_FIELD_NUMBER = 255;
    private Common.BaseReq baseReq_;
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    @Override
    public boolean hasBaseReq() {
      return baseReq_ != null;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    @Override
    public Common.BaseReq getBaseReq() {
      return baseReq_ == null ? Common.BaseReq.getDefaultInstance() : baseReq_;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    @Override
    public Common.BaseReqOrBuilder getBaseReqOrBuilder() {
      return getBaseReq();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeId_ != 0L) {
        output.writeInt64(1, nodeId_);
      }
      if (baseReq_ != null) {
        output.writeMessage(255, getBaseReq());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nodeId_);
      }
      if (baseReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseReq());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetNodeRequest)) {
        return super.equals(obj);
      }
      GetNodeRequest other = (GetNodeRequest) obj;

      if (getNodeId()
          != other.getNodeId()) return false;
      if (hasBaseReq() != other.hasBaseReq()) return false;
      if (hasBaseReq()) {
        if (!getBaseReq()
            .equals(other.getBaseReq())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNodeId());
      if (hasBaseReq()) {
        hash = (37 * hash) + BASEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getBaseReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetNodeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetNodeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetNodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetNodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetNodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetNodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetNodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetNodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetNodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetNodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetNodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetNodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetNodeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetNodeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetNodeRequest)
        GetNodeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetNode.internal_static_GetNodeRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetNode.internal_static_GetNodeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetNodeRequest.class, Builder.class);
      }

      // Construct using com.graduate.design.proto.GetNode.GetNodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        nodeId_ = 0L;

        if (baseReqBuilder_ == null) {
          baseReq_ = null;
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetNode.internal_static_GetNodeRequest_descriptor;
      }

      @Override
      public GetNodeRequest getDefaultInstanceForType() {
        return GetNodeRequest.getDefaultInstance();
      }

      @Override
      public GetNodeRequest build() {
        GetNodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetNodeRequest buildPartial() {
        GetNodeRequest result = new GetNodeRequest(this);
        result.nodeId_ = nodeId_;
        if (baseReqBuilder_ == null) {
          result.baseReq_ = baseReq_;
        } else {
          result.baseReq_ = baseReqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetNodeRequest) {
          return mergeFrom((GetNodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetNodeRequest other) {
        if (other == GetNodeRequest.getDefaultInstance()) return this;
        if (other.getNodeId() != 0L) {
          setNodeId(other.getNodeId());
        }
        if (other.hasBaseReq()) {
          mergeBaseReq(other.getBaseReq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetNodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetNodeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long nodeId_ ;
      /**
       * <pre>
       * 节点id
       * </pre>
       *
       * <code>int64 nodeId = 1;</code>
       * @return The nodeId.
       */
      @Override
      public long getNodeId() {
        return nodeId_;
      }
      /**
       * <pre>
       * 节点id
       * </pre>
       *
       * <code>int64 nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(long value) {
        
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点id
       * </pre>
       *
       * <code>int64 nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        
        nodeId_ = 0L;
        onChanged();
        return this;
      }

      private Common.BaseReq baseReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseReq, Common.BaseReq.Builder, Common.BaseReqOrBuilder> baseReqBuilder_;
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return Whether the baseReq field is set.
       */
      public boolean hasBaseReq() {
        return baseReqBuilder_ != null || baseReq_ != null;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return The baseReq.
       */
      public Common.BaseReq getBaseReq() {
        if (baseReqBuilder_ == null) {
          return baseReq_ == null ? Common.BaseReq.getDefaultInstance() : baseReq_;
        } else {
          return baseReqBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseReq_ = value;
          onChanged();
        } else {
          baseReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(
          Common.BaseReq.Builder builderForValue) {
        if (baseReqBuilder_ == null) {
          baseReq_ = builderForValue.build();
          onChanged();
        } else {
          baseReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder mergeBaseReq(Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (baseReq_ != null) {
            baseReq_ =
              Common.BaseReq.newBuilder(baseReq_).mergeFrom(value).buildPartial();
          } else {
            baseReq_ = value;
          }
          onChanged();
        } else {
          baseReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder clearBaseReq() {
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
          onChanged();
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Common.BaseReq.Builder getBaseReqBuilder() {
        
        onChanged();
        return getBaseReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Common.BaseReqOrBuilder getBaseReqOrBuilder() {
        if (baseReqBuilder_ != null) {
          return baseReqBuilder_.getMessageOrBuilder();
        } else {
          return baseReq_ == null ?
              Common.BaseReq.getDefaultInstance() : baseReq_;
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseReq, Common.BaseReq.Builder, Common.BaseReqOrBuilder>
          getBaseReqFieldBuilder() {
        if (baseReqBuilder_ == null) {
          baseReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Common.BaseReq, Common.BaseReq.Builder, Common.BaseReqOrBuilder>(
                  getBaseReq(),
                  getParentForChildren(),
                  isClean());
          baseReq_ = null;
        }
        return baseReqBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetNodeRequest)
    }

    // @@protoc_insertion_point(class_scope:GetNodeRequest)
    private static final GetNodeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetNodeRequest();
    }

    public static GetNodeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetNodeRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetNodeRequest>() {
      @Override
      public GetNodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetNodeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetNodeRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetNodeRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public GetNodeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetNodeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetNodeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 节点
     * </pre>
     *
     * <code>.Node node = 1;</code>
     * @return Whether the node field is set.
     */
    boolean hasNode();
    /**
     * <pre>
     * 节点
     * </pre>
     *
     * <code>.Node node = 1;</code>
     * @return The node.
     */
    Common.Node getNode();
    /**
     * <pre>
     * 节点
     * </pre>
     *
     * <code>.Node node = 1;</code>
     */
    Common.NodeOrBuilder getNodeOrBuilder();

    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    boolean hasBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    Common.BaseResp getBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    Common.BaseRespOrBuilder getBaseRespOrBuilder();
  }
  /**
   * Protobuf type {@code GetNodeResponse}
   */
  public static final class GetNodeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetNodeResponse)
      GetNodeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetNodeResponse.newBuilder() to construct.
    private GetNodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetNodeResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetNodeResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetNodeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Common.Node.Builder subBuilder = null;
              if (node_ != null) {
                subBuilder = node_.toBuilder();
              }
              node_ = input.readMessage(Common.Node.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(node_);
                node_ = subBuilder.buildPartial();
              }

              break;
            }
            case 2042: {
              Common.BaseResp.Builder subBuilder = null;
              if (baseResp_ != null) {
                subBuilder = baseResp_.toBuilder();
              }
              baseResp_ = input.readMessage(Common.BaseResp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResp_);
                baseResp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetNode.internal_static_GetNodeResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetNode.internal_static_GetNodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetNodeResponse.class, Builder.class);
    }

    public static final int NODE_FIELD_NUMBER = 1;
    private Common.Node node_;
    /**
     * <pre>
     * 节点
     * </pre>
     *
     * <code>.Node node = 1;</code>
     * @return Whether the node field is set.
     */
    @Override
    public boolean hasNode() {
      return node_ != null;
    }
    /**
     * <pre>
     * 节点
     * </pre>
     *
     * <code>.Node node = 1;</code>
     * @return The node.
     */
    @Override
    public Common.Node getNode() {
      return node_ == null ? Common.Node.getDefaultInstance() : node_;
    }
    /**
     * <pre>
     * 节点
     * </pre>
     *
     * <code>.Node node = 1;</code>
     */
    @Override
    public Common.NodeOrBuilder getNodeOrBuilder() {
      return getNode();
    }

    public static final int BASERESP_FIELD_NUMBER = 255;
    private Common.BaseResp baseResp_;
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    @Override
    public boolean hasBaseResp() {
      return baseResp_ != null;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    @Override
    public Common.BaseResp getBaseResp() {
      return baseResp_ == null ? Common.BaseResp.getDefaultInstance() : baseResp_;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    @Override
    public Common.BaseRespOrBuilder getBaseRespOrBuilder() {
      return getBaseResp();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (node_ != null) {
        output.writeMessage(1, getNode());
      }
      if (baseResp_ != null) {
        output.writeMessage(255, getBaseResp());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (node_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNode());
      }
      if (baseResp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetNodeResponse)) {
        return super.equals(obj);
      }
      GetNodeResponse other = (GetNodeResponse) obj;

      if (hasNode() != other.hasNode()) return false;
      if (hasNode()) {
        if (!getNode()
            .equals(other.getNode())) return false;
      }
      if (hasBaseResp() != other.hasBaseResp()) return false;
      if (hasBaseResp()) {
        if (!getBaseResp()
            .equals(other.getBaseResp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNode()) {
        hash = (37 * hash) + NODE_FIELD_NUMBER;
        hash = (53 * hash) + getNode().hashCode();
      }
      if (hasBaseResp()) {
        hash = (37 * hash) + BASERESP_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetNodeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetNodeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetNodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetNodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetNodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetNodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetNodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetNodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetNodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetNodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetNodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetNodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetNodeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetNodeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetNodeResponse)
        GetNodeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetNode.internal_static_GetNodeResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetNode.internal_static_GetNodeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetNodeResponse.class, Builder.class);
      }

      // Construct using com.graduate.design.proto.GetNode.GetNodeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (nodeBuilder_ == null) {
          node_ = null;
        } else {
          node_ = null;
          nodeBuilder_ = null;
        }
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetNode.internal_static_GetNodeResponse_descriptor;
      }

      @Override
      public GetNodeResponse getDefaultInstanceForType() {
        return GetNodeResponse.getDefaultInstance();
      }

      @Override
      public GetNodeResponse build() {
        GetNodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetNodeResponse buildPartial() {
        GetNodeResponse result = new GetNodeResponse(this);
        if (nodeBuilder_ == null) {
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetNodeResponse) {
          return mergeFrom((GetNodeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetNodeResponse other) {
        if (other == GetNodeResponse.getDefaultInstance()) return this;
        if (other.hasNode()) {
          mergeNode(other.getNode());
        }
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetNodeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetNodeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Common.Node node_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.Node, Common.Node.Builder, Common.NodeOrBuilder> nodeBuilder_;
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       * @return Whether the node field is set.
       */
      public boolean hasNode() {
        return nodeBuilder_ != null || node_ != null;
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       * @return The node.
       */
      public Common.Node getNode() {
        if (nodeBuilder_ == null) {
          return node_ == null ? Common.Node.getDefaultInstance() : node_;
        } else {
          return nodeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      public Builder setNode(Common.Node value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          nodeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      public Builder setNode(
          Common.Node.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          nodeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      public Builder mergeNode(Common.Node value) {
        if (nodeBuilder_ == null) {
          if (node_ != null) {
            node_ =
              Common.Node.newBuilder(node_).mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          nodeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = null;
          onChanged();
        } else {
          node_ = null;
          nodeBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      public Common.Node.Builder getNodeBuilder() {
        
        onChanged();
        return getNodeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      public Common.NodeOrBuilder getNodeOrBuilder() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilder();
        } else {
          return node_ == null ?
              Common.Node.getDefaultInstance() : node_;
        }
      }
      /**
       * <pre>
       * 节点
       * </pre>
       *
       * <code>.Node node = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.Node, Common.Node.Builder, Common.NodeOrBuilder>
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Common.Node, Common.Node.Builder, Common.NodeOrBuilder>(
                  getNode(),
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }

      private Common.BaseResp baseResp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseResp, Common.BaseResp.Builder, Common.BaseRespOrBuilder> baseRespBuilder_;
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return Whether the baseResp field is set.
       */
      public boolean hasBaseResp() {
        return baseRespBuilder_ != null || baseResp_ != null;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return The baseResp.
       */
      public Common.BaseResp getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_ == null ? Common.BaseResp.getDefaultInstance() : baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(
          Common.BaseResp.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder mergeBaseResp(Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (baseResp_ != null) {
            baseResp_ =
              Common.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
          onChanged();
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Common.BaseResp.Builder getBaseRespBuilder() {
        
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Common.BaseRespOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_ == null ?
              Common.BaseResp.getDefaultInstance() : baseResp_;
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseResp, Common.BaseResp.Builder, Common.BaseRespOrBuilder>
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Common.BaseResp, Common.BaseResp.Builder, Common.BaseRespOrBuilder>(
                  getBaseResp(),
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetNodeResponse)
    }

    // @@protoc_insertion_point(class_scope:GetNodeResponse)
    private static final GetNodeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetNodeResponse();
    }

    public static GetNodeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetNodeResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetNodeResponse>() {
      @Override
      public GetNodeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetNodeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetNodeResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetNodeResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public GetNodeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetNodeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetNodeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetNodeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetNodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016get_node.proto\032\014common.proto\"<\n\016GetNod" +
      "eRequest\022\016\n\006nodeId\030\001 \001(\003\022\032\n\007baseReq\030\377\001 \001" +
      "(\0132\010.BaseReq\"D\n\017GetNodeResponse\022\023\n\004node\030" +
      "\001 \001(\0132\005.Node\022\034\n\010baseResp\030\377\001 \001(\0132\t.BaseRe" +
      "spB.\n\031com.graduate.design.protoB\007GetNode" +
      "Z\010./pb_genb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.getDescriptor(),
        });
    internal_static_GetNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetNodeRequest_descriptor,
        new String[] { "NodeId", "BaseReq", });
    internal_static_GetNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetNodeResponse_descriptor,
        new String[] { "Node", "BaseResp", });
    Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
