// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_recv_file.proto

package com.graduate.design.proto;

public final class GetRecvFile {
  private GetRecvFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SharedFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SharedFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 此条分享记录的id
     * </pre>
     *
     * <code>int64 shareId = 1;</code>
     * @return The shareId.
     */
    long getShareId();

    /**
     * <code>int64 fileId = 2;</code>
     * @return The fileId.
     */
    long getFileId();

    /**
     * <code>string fileName = 3;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 3;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <pre>
     * 解密文件用的key
     * </pre>
     *
     * <code>bytes key = 4;</code>
     * @return The key.
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <pre>
     * 文件来自谁? 
     * </pre>
     *
     * <code>string from = 5;</code>
     * @return The from.
     */
    java.lang.String getFrom();
    /**
     * <pre>
     * 文件来自谁? 
     * </pre>
     *
     * <code>string from = 5;</code>
     * @return The bytes for from.
     */
    com.google.protobuf.ByteString
        getFromBytes();
  }
  /**
   * <pre>
   * 前端分享的文件
   * </pre>
   *
   * Protobuf type {@code SharedFile}
   */
  public static final class SharedFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SharedFile)
      SharedFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SharedFile.newBuilder() to construct.
    private SharedFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SharedFile() {
      fileName_ = "";
      key_ = com.google.protobuf.ByteString.EMPTY;
      from_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SharedFile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SharedFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              shareId_ = input.readInt64();
              break;
            }
            case 16: {

              fileId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 34: {

              key_ = input.readBytes();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.GetRecvFile.internal_static_SharedFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.GetRecvFile.internal_static_SharedFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.GetRecvFile.SharedFile.class, com.graduate.design.proto.GetRecvFile.SharedFile.Builder.class);
    }

    public static final int SHAREID_FIELD_NUMBER = 1;
    private long shareId_;
    /**
     * <pre>
     * 此条分享记录的id
     * </pre>
     *
     * <code>int64 shareId = 1;</code>
     * @return The shareId.
     */
    @java.lang.Override
    public long getShareId() {
      return shareId_;
    }

    public static final int FILEID_FIELD_NUMBER = 2;
    private long fileId_;
    /**
     * <code>int64 fileId = 2;</code>
     * @return The fileId.
     */
    @java.lang.Override
    public long getFileId() {
      return fileId_;
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 3;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 3;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString key_;
    /**
     * <pre>
     * 解密文件用的key
     * </pre>
     *
     * <code>bytes key = 4;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int FROM_FIELD_NUMBER = 5;
    private volatile java.lang.Object from_;
    /**
     * <pre>
     * 文件来自谁? 
     * </pre>
     *
     * <code>string from = 5;</code>
     * @return The from.
     */
    @java.lang.Override
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文件来自谁? 
     * </pre>
     *
     * <code>string from = 5;</code>
     * @return The bytes for from.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (shareId_ != 0L) {
        output.writeInt64(1, shareId_);
      }
      if (fileId_ != 0L) {
        output.writeInt64(2, fileId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
      }
      if (!key_.isEmpty()) {
        output.writeBytes(4, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, from_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (shareId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, shareId_);
      }
      if (fileId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fileId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
      }
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, from_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.GetRecvFile.SharedFile)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.GetRecvFile.SharedFile other = (com.graduate.design.proto.GetRecvFile.SharedFile) obj;

      if (getShareId()
          != other.getShareId()) return false;
      if (getFileId()
          != other.getFileId()) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getFrom()
          .equals(other.getFrom())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SHAREID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShareId());
      hash = (37 * hash) + FILEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileId());
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.SharedFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.GetRecvFile.SharedFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 前端分享的文件
     * </pre>
     *
     * Protobuf type {@code SharedFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SharedFile)
        com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.GetRecvFile.internal_static_SharedFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.GetRecvFile.internal_static_SharedFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.GetRecvFile.SharedFile.class, com.graduate.design.proto.GetRecvFile.SharedFile.Builder.class);
      }

      // Construct using com.graduate.design.proto.GetRecvFile.SharedFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        shareId_ = 0L;

        fileId_ = 0L;

        fileName_ = "";

        key_ = com.google.protobuf.ByteString.EMPTY;

        from_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.GetRecvFile.internal_static_SharedFile_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.SharedFile getDefaultInstanceForType() {
        return com.graduate.design.proto.GetRecvFile.SharedFile.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.SharedFile build() {
        com.graduate.design.proto.GetRecvFile.SharedFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.SharedFile buildPartial() {
        com.graduate.design.proto.GetRecvFile.SharedFile result = new com.graduate.design.proto.GetRecvFile.SharedFile(this);
        result.shareId_ = shareId_;
        result.fileId_ = fileId_;
        result.fileName_ = fileName_;
        result.key_ = key_;
        result.from_ = from_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.GetRecvFile.SharedFile) {
          return mergeFrom((com.graduate.design.proto.GetRecvFile.SharedFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.GetRecvFile.SharedFile other) {
        if (other == com.graduate.design.proto.GetRecvFile.SharedFile.getDefaultInstance()) return this;
        if (other.getShareId() != 0L) {
          setShareId(other.getShareId());
        }
        if (other.getFileId() != 0L) {
          setFileId(other.getFileId());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
          setKey(other.getKey());
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.GetRecvFile.SharedFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.GetRecvFile.SharedFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long shareId_ ;
      /**
       * <pre>
       * 此条分享记录的id
       * </pre>
       *
       * <code>int64 shareId = 1;</code>
       * @return The shareId.
       */
      @java.lang.Override
      public long getShareId() {
        return shareId_;
      }
      /**
       * <pre>
       * 此条分享记录的id
       * </pre>
       *
       * <code>int64 shareId = 1;</code>
       * @param value The shareId to set.
       * @return This builder for chaining.
       */
      public Builder setShareId(long value) {
        
        shareId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 此条分享记录的id
       * </pre>
       *
       * <code>int64 shareId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearShareId() {
        
        shareId_ = 0L;
        onChanged();
        return this;
      }

      private long fileId_ ;
      /**
       * <code>int64 fileId = 2;</code>
       * @return The fileId.
       */
      @java.lang.Override
      public long getFileId() {
        return fileId_;
      }
      /**
       * <code>int64 fileId = 2;</code>
       * @param value The fileId to set.
       * @return This builder for chaining.
       */
      public Builder setFileId(long value) {
        
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fileId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileId() {
        
        fileId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 3;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 解密文件用的key
       * </pre>
       *
       * <code>bytes key = 4;</code>
       * @return The key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <pre>
       * 解密文件用的key
       * </pre>
       *
       * <code>bytes key = 4;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 解密文件用的key
       * </pre>
       *
       * <code>bytes key = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <pre>
       * 文件来自谁? 
       * </pre>
       *
       * <code>string from = 5;</code>
       * @return The from.
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 文件来自谁? 
       * </pre>
       *
       * <code>string from = 5;</code>
       * @return The bytes for from.
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文件来自谁? 
       * </pre>
       *
       * <code>string from = 5;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件来自谁? 
       * </pre>
       *
       * <code>string from = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件来自谁? 
       * </pre>
       *
       * <code>string from = 5;</code>
       * @param value The bytes for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SharedFile)
    }

    // @@protoc_insertion_point(class_scope:SharedFile)
    private static final com.graduate.design.proto.GetRecvFile.SharedFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.GetRecvFile.SharedFile();
    }

    public static com.graduate.design.proto.GetRecvFile.SharedFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SharedFile>
        PARSER = new com.google.protobuf.AbstractParser<SharedFile>() {
      @java.lang.Override
      public SharedFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SharedFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SharedFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SharedFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.GetRecvFile.SharedFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRecvFileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetRecvFileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    boolean hasBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    com.graduate.design.proto.Common.BaseReq getBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder();
  }
  /**
   * Protobuf type {@code GetRecvFileRequest}
   */
  public static final class GetRecvFileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetRecvFileRequest)
      GetRecvFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRecvFileRequest.newBuilder() to construct.
    private GetRecvFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRecvFileRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetRecvFileRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetRecvFileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 2042: {
              com.graduate.design.proto.Common.BaseReq.Builder subBuilder = null;
              if (baseReq_ != null) {
                subBuilder = baseReq_.toBuilder();
              }
              baseReq_ = input.readMessage(com.graduate.design.proto.Common.BaseReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseReq_);
                baseReq_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.class, com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.Builder.class);
    }

    public static final int BASEREQ_FIELD_NUMBER = 255;
    private com.graduate.design.proto.Common.BaseReq baseReq_;
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    @java.lang.Override
    public boolean hasBaseReq() {
      return baseReq_ != null;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseReq getBaseReq() {
      return baseReq_ == null ? com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder() {
      return getBaseReq();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseReq_ != null) {
        output.writeMessage(255, getBaseReq());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseReq());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.GetRecvFile.GetRecvFileRequest)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.GetRecvFile.GetRecvFileRequest other = (com.graduate.design.proto.GetRecvFile.GetRecvFileRequest) obj;

      if (hasBaseReq() != other.hasBaseReq()) return false;
      if (hasBaseReq()) {
        if (!getBaseReq()
            .equals(other.getBaseReq())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseReq()) {
        hash = (37 * hash) + BASEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getBaseReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.GetRecvFile.GetRecvFileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRecvFileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetRecvFileRequest)
        com.graduate.design.proto.GetRecvFile.GetRecvFileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.class, com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.Builder.class);
      }

      // Construct using com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileRequest_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.GetRecvFileRequest getDefaultInstanceForType() {
        return com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.GetRecvFileRequest build() {
        com.graduate.design.proto.GetRecvFile.GetRecvFileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.GetRecvFileRequest buildPartial() {
        com.graduate.design.proto.GetRecvFile.GetRecvFileRequest result = new com.graduate.design.proto.GetRecvFile.GetRecvFileRequest(this);
        if (baseReqBuilder_ == null) {
          result.baseReq_ = baseReq_;
        } else {
          result.baseReq_ = baseReqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.GetRecvFile.GetRecvFileRequest) {
          return mergeFrom((com.graduate.design.proto.GetRecvFile.GetRecvFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.GetRecvFile.GetRecvFileRequest other) {
        if (other == com.graduate.design.proto.GetRecvFile.GetRecvFileRequest.getDefaultInstance()) return this;
        if (other.hasBaseReq()) {
          mergeBaseReq(other.getBaseReq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.GetRecvFile.GetRecvFileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.GetRecvFile.GetRecvFileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.graduate.design.proto.Common.BaseReq baseReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder> baseReqBuilder_;
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return Whether the baseReq field is set.
       */
      public boolean hasBaseReq() {
        return baseReqBuilder_ != null || baseReq_ != null;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return The baseReq.
       */
      public com.graduate.design.proto.Common.BaseReq getBaseReq() {
        if (baseReqBuilder_ == null) {
          return baseReq_ == null ? com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
        } else {
          return baseReqBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(com.graduate.design.proto.Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseReq_ = value;
          onChanged();
        } else {
          baseReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(
          com.graduate.design.proto.Common.BaseReq.Builder builderForValue) {
        if (baseReqBuilder_ == null) {
          baseReq_ = builderForValue.build();
          onChanged();
        } else {
          baseReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder mergeBaseReq(com.graduate.design.proto.Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (baseReq_ != null) {
            baseReq_ =
              com.graduate.design.proto.Common.BaseReq.newBuilder(baseReq_).mergeFrom(value).buildPartial();
          } else {
            baseReq_ = value;
          }
          onChanged();
        } else {
          baseReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder clearBaseReq() {
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
          onChanged();
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseReq.Builder getBaseReqBuilder() {
        
        onChanged();
        return getBaseReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseReqOrBuilder getBaseReqOrBuilder() {
        if (baseReqBuilder_ != null) {
          return baseReqBuilder_.getMessageOrBuilder();
        } else {
          return baseReq_ == null ?
              com.graduate.design.proto.Common.BaseReq.getDefaultInstance() : baseReq_;
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder> 
          getBaseReqFieldBuilder() {
        if (baseReqBuilder_ == null) {
          baseReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.graduate.design.proto.Common.BaseReq, com.graduate.design.proto.Common.BaseReq.Builder, com.graduate.design.proto.Common.BaseReqOrBuilder>(
                  getBaseReq(),
                  getParentForChildren(),
                  isClean());
          baseReq_ = null;
        }
        return baseReqBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetRecvFileRequest)
    }

    // @@protoc_insertion_point(class_scope:GetRecvFileRequest)
    private static final com.graduate.design.proto.GetRecvFile.GetRecvFileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.GetRecvFile.GetRecvFileRequest();
    }

    public static com.graduate.design.proto.GetRecvFile.GetRecvFileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRecvFileRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetRecvFileRequest>() {
      @java.lang.Override
      public GetRecvFileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRecvFileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRecvFileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRecvFileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.GetRecvFile.GetRecvFileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRecvFileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetRecvFileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    java.util.List<com.graduate.design.proto.GetRecvFile.SharedFile> 
        getShareFileListList();
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    com.graduate.design.proto.GetRecvFile.SharedFile getShareFileList(int index);
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    int getShareFileListCount();
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    java.util.List<? extends com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder> 
        getShareFileListOrBuilderList();
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder getShareFileListOrBuilder(
        int index);

    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    boolean hasBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    com.graduate.design.proto.Common.BaseResp getBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder();
  }
  /**
   * Protobuf type {@code GetRecvFileResponse}
   */
  public static final class GetRecvFileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetRecvFileResponse)
      GetRecvFileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRecvFileResponse.newBuilder() to construct.
    private GetRecvFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRecvFileResponse() {
      shareFileList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetRecvFileResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetRecvFileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                shareFileList_ = new java.util.ArrayList<com.graduate.design.proto.GetRecvFile.SharedFile>();
                mutable_bitField0_ |= 0x00000001;
              }
              shareFileList_.add(
                  input.readMessage(com.graduate.design.proto.GetRecvFile.SharedFile.parser(), extensionRegistry));
              break;
            }
            case 2042: {
              com.graduate.design.proto.Common.BaseResp.Builder subBuilder = null;
              if (baseResp_ != null) {
                subBuilder = baseResp_.toBuilder();
              }
              baseResp_ = input.readMessage(com.graduate.design.proto.Common.BaseResp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResp_);
                baseResp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          shareFileList_ = java.util.Collections.unmodifiableList(shareFileList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.class, com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.Builder.class);
    }

    public static final int SHAREFILELIST_FIELD_NUMBER = 1;
    private java.util.List<com.graduate.design.proto.GetRecvFile.SharedFile> shareFileList_;
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.graduate.design.proto.GetRecvFile.SharedFile> getShareFileListList() {
      return shareFileList_;
    }
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder> 
        getShareFileListOrBuilderList() {
      return shareFileList_;
    }
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    @java.lang.Override
    public int getShareFileListCount() {
      return shareFileList_.size();
    }
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.GetRecvFile.SharedFile getShareFileList(int index) {
      return shareFileList_.get(index);
    }
    /**
     * <code>repeated .SharedFile shareFileList = 1;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder getShareFileListOrBuilder(
        int index) {
      return shareFileList_.get(index);
    }

    public static final int BASERESP_FIELD_NUMBER = 255;
    private com.graduate.design.proto.Common.BaseResp baseResp_;
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    @java.lang.Override
    public boolean hasBaseResp() {
      return baseResp_ != null;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseResp getBaseResp() {
      return baseResp_ == null ? com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    @java.lang.Override
    public com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder() {
      return getBaseResp();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < shareFileList_.size(); i++) {
        output.writeMessage(1, shareFileList_.get(i));
      }
      if (baseResp_ != null) {
        output.writeMessage(255, getBaseResp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < shareFileList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, shareFileList_.get(i));
      }
      if (baseResp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.graduate.design.proto.GetRecvFile.GetRecvFileResponse)) {
        return super.equals(obj);
      }
      com.graduate.design.proto.GetRecvFile.GetRecvFileResponse other = (com.graduate.design.proto.GetRecvFile.GetRecvFileResponse) obj;

      if (!getShareFileListList()
          .equals(other.getShareFileListList())) return false;
      if (hasBaseResp() != other.hasBaseResp()) return false;
      if (hasBaseResp()) {
        if (!getBaseResp()
            .equals(other.getBaseResp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getShareFileListCount() > 0) {
        hash = (37 * hash) + SHAREFILELIST_FIELD_NUMBER;
        hash = (53 * hash) + getShareFileListList().hashCode();
      }
      if (hasBaseResp()) {
        hash = (37 * hash) + BASERESP_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.graduate.design.proto.GetRecvFile.GetRecvFileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRecvFileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetRecvFileResponse)
        com.graduate.design.proto.GetRecvFile.GetRecvFileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.class, com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.Builder.class);
      }

      // Construct using com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getShareFileListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (shareFileListBuilder_ == null) {
          shareFileList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          shareFileListBuilder_.clear();
        }
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.graduate.design.proto.GetRecvFile.internal_static_GetRecvFileResponse_descriptor;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.GetRecvFileResponse getDefaultInstanceForType() {
        return com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.GetRecvFileResponse build() {
        com.graduate.design.proto.GetRecvFile.GetRecvFileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.graduate.design.proto.GetRecvFile.GetRecvFileResponse buildPartial() {
        com.graduate.design.proto.GetRecvFile.GetRecvFileResponse result = new com.graduate.design.proto.GetRecvFile.GetRecvFileResponse(this);
        int from_bitField0_ = bitField0_;
        if (shareFileListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            shareFileList_ = java.util.Collections.unmodifiableList(shareFileList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.shareFileList_ = shareFileList_;
        } else {
          result.shareFileList_ = shareFileListBuilder_.build();
        }
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.graduate.design.proto.GetRecvFile.GetRecvFileResponse) {
          return mergeFrom((com.graduate.design.proto.GetRecvFile.GetRecvFileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.graduate.design.proto.GetRecvFile.GetRecvFileResponse other) {
        if (other == com.graduate.design.proto.GetRecvFile.GetRecvFileResponse.getDefaultInstance()) return this;
        if (shareFileListBuilder_ == null) {
          if (!other.shareFileList_.isEmpty()) {
            if (shareFileList_.isEmpty()) {
              shareFileList_ = other.shareFileList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureShareFileListIsMutable();
              shareFileList_.addAll(other.shareFileList_);
            }
            onChanged();
          }
        } else {
          if (!other.shareFileList_.isEmpty()) {
            if (shareFileListBuilder_.isEmpty()) {
              shareFileListBuilder_.dispose();
              shareFileListBuilder_ = null;
              shareFileList_ = other.shareFileList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              shareFileListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getShareFileListFieldBuilder() : null;
            } else {
              shareFileListBuilder_.addAllMessages(other.shareFileList_);
            }
          }
        }
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.graduate.design.proto.GetRecvFile.GetRecvFileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.graduate.design.proto.GetRecvFile.GetRecvFileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.graduate.design.proto.GetRecvFile.SharedFile> shareFileList_ =
        java.util.Collections.emptyList();
      private void ensureShareFileListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          shareFileList_ = new java.util.ArrayList<com.graduate.design.proto.GetRecvFile.SharedFile>(shareFileList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.graduate.design.proto.GetRecvFile.SharedFile, com.graduate.design.proto.GetRecvFile.SharedFile.Builder, com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder> shareFileListBuilder_;

      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public java.util.List<com.graduate.design.proto.GetRecvFile.SharedFile> getShareFileListList() {
        if (shareFileListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(shareFileList_);
        } else {
          return shareFileListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public int getShareFileListCount() {
        if (shareFileListBuilder_ == null) {
          return shareFileList_.size();
        } else {
          return shareFileListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public com.graduate.design.proto.GetRecvFile.SharedFile getShareFileList(int index) {
        if (shareFileListBuilder_ == null) {
          return shareFileList_.get(index);
        } else {
          return shareFileListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder setShareFileList(
          int index, com.graduate.design.proto.GetRecvFile.SharedFile value) {
        if (shareFileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShareFileListIsMutable();
          shareFileList_.set(index, value);
          onChanged();
        } else {
          shareFileListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder setShareFileList(
          int index, com.graduate.design.proto.GetRecvFile.SharedFile.Builder builderForValue) {
        if (shareFileListBuilder_ == null) {
          ensureShareFileListIsMutable();
          shareFileList_.set(index, builderForValue.build());
          onChanged();
        } else {
          shareFileListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder addShareFileList(com.graduate.design.proto.GetRecvFile.SharedFile value) {
        if (shareFileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShareFileListIsMutable();
          shareFileList_.add(value);
          onChanged();
        } else {
          shareFileListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder addShareFileList(
          int index, com.graduate.design.proto.GetRecvFile.SharedFile value) {
        if (shareFileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShareFileListIsMutable();
          shareFileList_.add(index, value);
          onChanged();
        } else {
          shareFileListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder addShareFileList(
          com.graduate.design.proto.GetRecvFile.SharedFile.Builder builderForValue) {
        if (shareFileListBuilder_ == null) {
          ensureShareFileListIsMutable();
          shareFileList_.add(builderForValue.build());
          onChanged();
        } else {
          shareFileListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder addShareFileList(
          int index, com.graduate.design.proto.GetRecvFile.SharedFile.Builder builderForValue) {
        if (shareFileListBuilder_ == null) {
          ensureShareFileListIsMutable();
          shareFileList_.add(index, builderForValue.build());
          onChanged();
        } else {
          shareFileListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder addAllShareFileList(
          java.lang.Iterable<? extends com.graduate.design.proto.GetRecvFile.SharedFile> values) {
        if (shareFileListBuilder_ == null) {
          ensureShareFileListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, shareFileList_);
          onChanged();
        } else {
          shareFileListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder clearShareFileList() {
        if (shareFileListBuilder_ == null) {
          shareFileList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          shareFileListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public Builder removeShareFileList(int index) {
        if (shareFileListBuilder_ == null) {
          ensureShareFileListIsMutable();
          shareFileList_.remove(index);
          onChanged();
        } else {
          shareFileListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public com.graduate.design.proto.GetRecvFile.SharedFile.Builder getShareFileListBuilder(
          int index) {
        return getShareFileListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder getShareFileListOrBuilder(
          int index) {
        if (shareFileListBuilder_ == null) {
          return shareFileList_.get(index);  } else {
          return shareFileListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public java.util.List<? extends com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder> 
           getShareFileListOrBuilderList() {
        if (shareFileListBuilder_ != null) {
          return shareFileListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(shareFileList_);
        }
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public com.graduate.design.proto.GetRecvFile.SharedFile.Builder addShareFileListBuilder() {
        return getShareFileListFieldBuilder().addBuilder(
            com.graduate.design.proto.GetRecvFile.SharedFile.getDefaultInstance());
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public com.graduate.design.proto.GetRecvFile.SharedFile.Builder addShareFileListBuilder(
          int index) {
        return getShareFileListFieldBuilder().addBuilder(
            index, com.graduate.design.proto.GetRecvFile.SharedFile.getDefaultInstance());
      }
      /**
       * <code>repeated .SharedFile shareFileList = 1;</code>
       */
      public java.util.List<com.graduate.design.proto.GetRecvFile.SharedFile.Builder> 
           getShareFileListBuilderList() {
        return getShareFileListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.graduate.design.proto.GetRecvFile.SharedFile, com.graduate.design.proto.GetRecvFile.SharedFile.Builder, com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder> 
          getShareFileListFieldBuilder() {
        if (shareFileListBuilder_ == null) {
          shareFileListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.graduate.design.proto.GetRecvFile.SharedFile, com.graduate.design.proto.GetRecvFile.SharedFile.Builder, com.graduate.design.proto.GetRecvFile.SharedFileOrBuilder>(
                  shareFileList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          shareFileList_ = null;
        }
        return shareFileListBuilder_;
      }

      private com.graduate.design.proto.Common.BaseResp baseResp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder> baseRespBuilder_;
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return Whether the baseResp field is set.
       */
      public boolean hasBaseResp() {
        return baseRespBuilder_ != null || baseResp_ != null;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return The baseResp.
       */
      public com.graduate.design.proto.Common.BaseResp getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_ == null ? com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(com.graduate.design.proto.Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(
          com.graduate.design.proto.Common.BaseResp.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder mergeBaseResp(com.graduate.design.proto.Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (baseResp_ != null) {
            baseResp_ =
              com.graduate.design.proto.Common.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
          onChanged();
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseResp.Builder getBaseRespBuilder() {
        
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public com.graduate.design.proto.Common.BaseRespOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_ == null ?
              com.graduate.design.proto.Common.BaseResp.getDefaultInstance() : baseResp_;
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder> 
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.graduate.design.proto.Common.BaseResp, com.graduate.design.proto.Common.BaseResp.Builder, com.graduate.design.proto.Common.BaseRespOrBuilder>(
                  getBaseResp(),
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetRecvFileResponse)
    }

    // @@protoc_insertion_point(class_scope:GetRecvFileResponse)
    private static final com.graduate.design.proto.GetRecvFile.GetRecvFileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.graduate.design.proto.GetRecvFile.GetRecvFileResponse();
    }

    public static com.graduate.design.proto.GetRecvFile.GetRecvFileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRecvFileResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetRecvFileResponse>() {
      @java.lang.Override
      public GetRecvFileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRecvFileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRecvFileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRecvFileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.graduate.design.proto.GetRecvFile.GetRecvFileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SharedFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SharedFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRecvFileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRecvFileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRecvFileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRecvFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023get_recv_file.proto\032\014common.proto\"Z\n\nS" +
      "haredFile\022\017\n\007shareId\030\001 \001(\003\022\016\n\006fileId\030\002 \001" +
      "(\003\022\020\n\010fileName\030\003 \001(\t\022\013\n\003key\030\004 \001(\014\022\014\n\004fro" +
      "m\030\005 \001(\t\"0\n\022GetRecvFileRequest\022\032\n\007baseReq" +
      "\030\377\001 \001(\0132\010.BaseReq\"W\n\023GetRecvFileResponse" +
      "\022\"\n\rshareFileList\030\001 \003(\0132\013.SharedFile\022\034\n\010" +
      "baseResp\030\377\001 \001(\0132\t.BaseRespBP\n\031com.gradua" +
      "te.design.protoB\013GetRecvFileZ&github.com" +
      "/JackTJC/gmFS_backend/pb_genb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.graduate.design.proto.Common.getDescriptor(),
        });
    internal_static_SharedFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SharedFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SharedFile_descriptor,
        new java.lang.String[] { "ShareId", "FileId", "FileName", "Key", "From", });
    internal_static_GetRecvFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetRecvFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRecvFileRequest_descriptor,
        new java.lang.String[] { "BaseReq", });
    internal_static_GetRecvFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetRecvFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRecvFileResponse_descriptor,
        new java.lang.String[] { "ShareFileList", "BaseResp", });
    com.graduate.design.proto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
