// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_file.proto

package com.graduate.design.proto;

public final class SearchFile {
  private SearchFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchFileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchFileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 nodeId = 1;</code>
     * @return A list containing the nodeId.
     */
    java.util.List<Long> getNodeIdList();
    /**
     * <code>repeated int64 nodeId = 1;</code>
     * @return The count of nodeId.
     */
    int getNodeIdCount();
    /**
     * <code>repeated int64 nodeId = 1;</code>
     * @param index The index of the element to return.
     * @return The nodeId at the given index.
     */
    long getNodeId(int index);

    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    boolean hasBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    Common.BaseReq getBaseReq();
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    Common.BaseReqOrBuilder getBaseReqOrBuilder();
  }
  /**
   * <pre>
   * base64
   * </pre>
   *
   * Protobuf type {@code SearchFileRequest}
   */
  public static final class SearchFileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchFileRequest)
      SearchFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchFileRequest.newBuilder() to construct.
    private SearchFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchFileRequest() {
      nodeId_ = emptyLongList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchFileRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchFileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodeId_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeId_.addLong(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                nodeId_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                nodeId_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 2042: {
              Common.BaseReq.Builder subBuilder = null;
              if (baseReq_ != null) {
                subBuilder = baseReq_.toBuilder();
              }
              baseReq_ = input.readMessage(Common.BaseReq.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseReq_);
                baseReq_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodeId_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchFile.internal_static_SearchFileRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchFile.internal_static_SearchFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchFileRequest.class, Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.LongList nodeId_;
    /**
     * <code>repeated int64 nodeId = 1;</code>
     * @return A list containing the nodeId.
     */
    @Override
    public java.util.List<Long>
        getNodeIdList() {
      return nodeId_;
    }
    /**
     * <code>repeated int64 nodeId = 1;</code>
     * @return The count of nodeId.
     */
    public int getNodeIdCount() {
      return nodeId_.size();
    }
    /**
     * <code>repeated int64 nodeId = 1;</code>
     * @param index The index of the element to return.
     * @return The nodeId at the given index.
     */
    public long getNodeId(int index) {
      return nodeId_.getLong(index);
    }
    private int nodeIdMemoizedSerializedSize = -1;

    public static final int BASEREQ_FIELD_NUMBER = 255;
    private Common.BaseReq baseReq_;
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return Whether the baseReq field is set.
     */
    @Override
    public boolean hasBaseReq() {
      return baseReq_ != null;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     * @return The baseReq.
     */
    @Override
    public Common.BaseReq getBaseReq() {
      return baseReq_ == null ? Common.BaseReq.getDefaultInstance() : baseReq_;
    }
    /**
     * <code>.BaseReq baseReq = 255;</code>
     */
    @Override
    public Common.BaseReqOrBuilder getBaseReqOrBuilder() {
      return getBaseReq();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNodeIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(nodeIdMemoizedSerializedSize);
      }
      for (int i = 0; i < nodeId_.size(); i++) {
        output.writeInt64NoTag(nodeId_.getLong(i));
      }
      if (baseReq_ != null) {
        output.writeMessage(255, getBaseReq());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < nodeId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(nodeId_.getLong(i));
        }
        size += dataSize;
        if (!getNodeIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        nodeIdMemoizedSerializedSize = dataSize;
      }
      if (baseReq_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseReq());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SearchFileRequest)) {
        return super.equals(obj);
      }
      SearchFileRequest other = (SearchFileRequest) obj;

      if (!getNodeIdList()
          .equals(other.getNodeIdList())) return false;
      if (hasBaseReq() != other.hasBaseReq()) return false;
      if (hasBaseReq()) {
        if (!getBaseReq()
            .equals(other.getBaseReq())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeIdCount() > 0) {
        hash = (37 * hash) + NODEID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeIdList().hashCode();
      }
      if (hasBaseReq()) {
        hash = (37 * hash) + BASEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getBaseReq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SearchFileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchFileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SearchFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SearchFileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * base64
     * </pre>
     *
     * Protobuf type {@code SearchFileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchFileRequest)
        SearchFileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchFile.internal_static_SearchFileRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchFile.internal_static_SearchFileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SearchFileRequest.class, Builder.class);
      }

      // Construct using com.graduate.design.proto.SearchFile.SearchFileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        nodeId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchFile.internal_static_SearchFileRequest_descriptor;
      }

      @Override
      public SearchFileRequest getDefaultInstanceForType() {
        return SearchFileRequest.getDefaultInstance();
      }

      @Override
      public SearchFileRequest build() {
        SearchFileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SearchFileRequest buildPartial() {
        SearchFileRequest result = new SearchFileRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          nodeId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nodeId_ = nodeId_;
        if (baseReqBuilder_ == null) {
          result.baseReq_ = baseReq_;
        } else {
          result.baseReq_ = baseReqBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchFileRequest) {
          return mergeFrom((SearchFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchFileRequest other) {
        if (other == SearchFileRequest.getDefaultInstance()) return this;
        if (!other.nodeId_.isEmpty()) {
          if (nodeId_.isEmpty()) {
            nodeId_ = other.nodeId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodeIdIsMutable();
            nodeId_.addAll(other.nodeId_);
          }
          onChanged();
        }
        if (other.hasBaseReq()) {
          mergeBaseReq(other.getBaseReq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SearchFileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchFileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList nodeId_ = emptyLongList();
      private void ensureNodeIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodeId_ = mutableCopy(nodeId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @return A list containing the nodeId.
       */
      public java.util.List<Long>
          getNodeIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(nodeId_) : nodeId_;
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @return The count of nodeId.
       */
      public int getNodeIdCount() {
        return nodeId_.size();
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @param index The index of the element to return.
       * @return The nodeId at the given index.
       */
      public long getNodeId(int index) {
        return nodeId_.getLong(index);
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @param index The index to set the value at.
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          int index, long value) {
        ensureNodeIdIsMutable();
        nodeId_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @param value The nodeId to add.
       * @return This builder for chaining.
       */
      public Builder addNodeId(long value) {
        ensureNodeIdIsMutable();
        nodeId_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @param values The nodeId to add.
       * @return This builder for chaining.
       */
      public Builder addAllNodeId(
          Iterable<? extends Long> values) {
        ensureNodeIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodeId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private Common.BaseReq baseReq_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseReq, Common.BaseReq.Builder, Common.BaseReqOrBuilder> baseReqBuilder_;
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return Whether the baseReq field is set.
       */
      public boolean hasBaseReq() {
        return baseReqBuilder_ != null || baseReq_ != null;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       * @return The baseReq.
       */
      public Common.BaseReq getBaseReq() {
        if (baseReqBuilder_ == null) {
          return baseReq_ == null ? Common.BaseReq.getDefaultInstance() : baseReq_;
        } else {
          return baseReqBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseReq_ = value;
          onChanged();
        } else {
          baseReqBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder setBaseReq(
          Common.BaseReq.Builder builderForValue) {
        if (baseReqBuilder_ == null) {
          baseReq_ = builderForValue.build();
          onChanged();
        } else {
          baseReqBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder mergeBaseReq(Common.BaseReq value) {
        if (baseReqBuilder_ == null) {
          if (baseReq_ != null) {
            baseReq_ =
              Common.BaseReq.newBuilder(baseReq_).mergeFrom(value).buildPartial();
          } else {
            baseReq_ = value;
          }
          onChanged();
        } else {
          baseReqBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Builder clearBaseReq() {
        if (baseReqBuilder_ == null) {
          baseReq_ = null;
          onChanged();
        } else {
          baseReq_ = null;
          baseReqBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Common.BaseReq.Builder getBaseReqBuilder() {
        
        onChanged();
        return getBaseReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      public Common.BaseReqOrBuilder getBaseReqOrBuilder() {
        if (baseReqBuilder_ != null) {
          return baseReqBuilder_.getMessageOrBuilder();
        } else {
          return baseReq_ == null ?
              Common.BaseReq.getDefaultInstance() : baseReq_;
        }
      }
      /**
       * <code>.BaseReq baseReq = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseReq, Common.BaseReq.Builder, Common.BaseReqOrBuilder>
          getBaseReqFieldBuilder() {
        if (baseReqBuilder_ == null) {
          baseReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Common.BaseReq, Common.BaseReq.Builder, Common.BaseReqOrBuilder>(
                  getBaseReq(),
                  getParentForChildren(),
                  isClean());
          baseReq_ = null;
        }
        return baseReqBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchFileRequest)
    }

    // @@protoc_insertion_point(class_scope:SearchFileRequest)
    private static final SearchFileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SearchFileRequest();
    }

    public static SearchFileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchFileRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchFileRequest>() {
      @Override
      public SearchFileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchFileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchFileRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SearchFileRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public SearchFileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchFileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchFileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    java.util.List<Common.Node>
        getNodeListList();
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    Common.Node getNodeList(int index);
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    int getNodeListCount();
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    java.util.List<? extends Common.NodeOrBuilder>
        getNodeListOrBuilderList();
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    Common.NodeOrBuilder getNodeListOrBuilder(
        int index);

    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    boolean hasBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    Common.BaseResp getBaseResp();
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    Common.BaseRespOrBuilder getBaseRespOrBuilder();
  }
  /**
   * Protobuf type {@code SearchFileResponse}
   */
  public static final class SearchFileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchFileResponse)
      SearchFileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchFileResponse.newBuilder() to construct.
    private SearchFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchFileResponse() {
      nodeList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchFileResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchFileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodeList_ = new java.util.ArrayList<Common.Node>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeList_.add(
                  input.readMessage(Common.Node.parser(), extensionRegistry));
              break;
            }
            case 2042: {
              Common.BaseResp.Builder subBuilder = null;
              if (baseResp_ != null) {
                subBuilder = baseResp_.toBuilder();
              }
              baseResp_ = input.readMessage(Common.BaseResp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseResp_);
                baseResp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodeList_ = java.util.Collections.unmodifiableList(nodeList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchFile.internal_static_SearchFileResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchFile.internal_static_SearchFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchFileResponse.class, Builder.class);
    }

    public static final int NODELIST_FIELD_NUMBER = 1;
    private java.util.List<Common.Node> nodeList_;
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    @Override
    public java.util.List<Common.Node> getNodeListList() {
      return nodeList_;
    }
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    @Override
    public java.util.List<? extends Common.NodeOrBuilder>
        getNodeListOrBuilderList() {
      return nodeList_;
    }
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    @Override
    public int getNodeListCount() {
      return nodeList_.size();
    }
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    @Override
    public Common.Node getNodeList(int index) {
      return nodeList_.get(index);
    }
    /**
     * <pre>
     * 搜索结果
     * </pre>
     *
     * <code>repeated .Node nodeList = 1;</code>
     */
    @Override
    public Common.NodeOrBuilder getNodeListOrBuilder(
        int index) {
      return nodeList_.get(index);
    }

    public static final int BASERESP_FIELD_NUMBER = 255;
    private Common.BaseResp baseResp_;
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return Whether the baseResp field is set.
     */
    @Override
    public boolean hasBaseResp() {
      return baseResp_ != null;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     * @return The baseResp.
     */
    @Override
    public Common.BaseResp getBaseResp() {
      return baseResp_ == null ? Common.BaseResp.getDefaultInstance() : baseResp_;
    }
    /**
     * <code>.BaseResp baseResp = 255;</code>
     */
    @Override
    public Common.BaseRespOrBuilder getBaseRespOrBuilder() {
      return getBaseResp();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodeList_.size(); i++) {
        output.writeMessage(1, nodeList_.get(i));
      }
      if (baseResp_ != null) {
        output.writeMessage(255, getBaseResp());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodeList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodeList_.get(i));
      }
      if (baseResp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBaseResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SearchFileResponse)) {
        return super.equals(obj);
      }
      SearchFileResponse other = (SearchFileResponse) obj;

      if (!getNodeListList()
          .equals(other.getNodeListList())) return false;
      if (hasBaseResp() != other.hasBaseResp()) return false;
      if (hasBaseResp()) {
        if (!getBaseResp()
            .equals(other.getBaseResp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeListCount() > 0) {
        hash = (37 * hash) + NODELIST_FIELD_NUMBER;
        hash = (53 * hash) + getNodeListList().hashCode();
      }
      if (hasBaseResp()) {
        hash = (37 * hash) + BASERESP_FIELD_NUMBER;
        hash = (53 * hash) + getBaseResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SearchFileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchFileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchFileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchFileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchFileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchFileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchFileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchFileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchFileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SearchFileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SearchFileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchFileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchFileResponse)
        SearchFileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchFile.internal_static_SearchFileResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchFile.internal_static_SearchFileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SearchFileResponse.class, Builder.class);
      }

      // Construct using com.graduate.design.proto.SearchFile.SearchFileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeListFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (nodeListBuilder_ == null) {
          nodeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeListBuilder_.clear();
        }
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchFile.internal_static_SearchFileResponse_descriptor;
      }

      @Override
      public SearchFileResponse getDefaultInstanceForType() {
        return SearchFileResponse.getDefaultInstance();
      }

      @Override
      public SearchFileResponse build() {
        SearchFileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SearchFileResponse buildPartial() {
        SearchFileResponse result = new SearchFileResponse(this);
        int from_bitField0_ = bitField0_;
        if (nodeListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            nodeList_ = java.util.Collections.unmodifiableList(nodeList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeList_ = nodeList_;
        } else {
          result.nodeList_ = nodeListBuilder_.build();
        }
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchFileResponse) {
          return mergeFrom((SearchFileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchFileResponse other) {
        if (other == SearchFileResponse.getDefaultInstance()) return this;
        if (nodeListBuilder_ == null) {
          if (!other.nodeList_.isEmpty()) {
            if (nodeList_.isEmpty()) {
              nodeList_ = other.nodeList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeListIsMutable();
              nodeList_.addAll(other.nodeList_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeList_.isEmpty()) {
            if (nodeListBuilder_.isEmpty()) {
              nodeListBuilder_.dispose();
              nodeListBuilder_ = null;
              nodeList_ = other.nodeList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeListFieldBuilder() : null;
            } else {
              nodeListBuilder_.addAllMessages(other.nodeList_);
            }
          }
        }
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SearchFileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchFileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Common.Node> nodeList_ =
        java.util.Collections.emptyList();
      private void ensureNodeListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodeList_ = new java.util.ArrayList<Common.Node>(nodeList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Common.Node, Common.Node.Builder, Common.NodeOrBuilder> nodeListBuilder_;

      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public java.util.List<Common.Node> getNodeListList() {
        if (nodeListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeList_);
        } else {
          return nodeListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public int getNodeListCount() {
        if (nodeListBuilder_ == null) {
          return nodeList_.size();
        } else {
          return nodeListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Common.Node getNodeList(int index) {
        if (nodeListBuilder_ == null) {
          return nodeList_.get(index);
        } else {
          return nodeListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder setNodeList(
          int index, Common.Node value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.set(index, value);
          onChanged();
        } else {
          nodeListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder setNodeList(
          int index, Common.Node.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder addNodeList(Common.Node value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.add(value);
          onChanged();
        } else {
          nodeListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder addNodeList(
          int index, Common.Node value) {
        if (nodeListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeListIsMutable();
          nodeList_.add(index, value);
          onChanged();
        } else {
          nodeListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder addNodeList(
          Common.Node.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.add(builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder addNodeList(
          int index, Common.Node.Builder builderForValue) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder addAllNodeList(
          Iterable<? extends Common.Node> values) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeList_);
          onChanged();
        } else {
          nodeListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder clearNodeList() {
        if (nodeListBuilder_ == null) {
          nodeList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Builder removeNodeList(int index) {
        if (nodeListBuilder_ == null) {
          ensureNodeListIsMutable();
          nodeList_.remove(index);
          onChanged();
        } else {
          nodeListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Common.Node.Builder getNodeListBuilder(
          int index) {
        return getNodeListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Common.NodeOrBuilder getNodeListOrBuilder(
          int index) {
        if (nodeListBuilder_ == null) {
          return nodeList_.get(index);  } else {
          return nodeListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public java.util.List<? extends Common.NodeOrBuilder>
           getNodeListOrBuilderList() {
        if (nodeListBuilder_ != null) {
          return nodeListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeList_);
        }
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Common.Node.Builder addNodeListBuilder() {
        return getNodeListFieldBuilder().addBuilder(
            Common.Node.getDefaultInstance());
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public Common.Node.Builder addNodeListBuilder(
          int index) {
        return getNodeListFieldBuilder().addBuilder(
            index, Common.Node.getDefaultInstance());
      }
      /**
       * <pre>
       * 搜索结果
       * </pre>
       *
       * <code>repeated .Node nodeList = 1;</code>
       */
      public java.util.List<Common.Node.Builder>
           getNodeListBuilderList() {
        return getNodeListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Common.Node, Common.Node.Builder, Common.NodeOrBuilder>
          getNodeListFieldBuilder() {
        if (nodeListBuilder_ == null) {
          nodeListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Common.Node, Common.Node.Builder, Common.NodeOrBuilder>(
                  nodeList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          nodeList_ = null;
        }
        return nodeListBuilder_;
      }

      private Common.BaseResp baseResp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseResp, Common.BaseResp.Builder, Common.BaseRespOrBuilder> baseRespBuilder_;
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return Whether the baseResp field is set.
       */
      public boolean hasBaseResp() {
        return baseRespBuilder_ != null || baseResp_ != null;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       * @return The baseResp.
       */
      public Common.BaseResp getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_ == null ? Common.BaseResp.getDefaultInstance() : baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder setBaseResp(
          Common.BaseResp.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder mergeBaseResp(Common.BaseResp value) {
        if (baseRespBuilder_ == null) {
          if (baseResp_ != null) {
            baseResp_ =
              Common.BaseResp.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = null;
          onChanged();
        } else {
          baseResp_ = null;
          baseRespBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Common.BaseResp.Builder getBaseRespBuilder() {
        
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      public Common.BaseRespOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_ == null ?
              Common.BaseResp.getDefaultInstance() : baseResp_;
        }
      }
      /**
       * <code>.BaseResp baseResp = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Common.BaseResp, Common.BaseResp.Builder, Common.BaseRespOrBuilder>
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Common.BaseResp, Common.BaseResp.Builder, Common.BaseRespOrBuilder>(
                  getBaseResp(),
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchFileResponse)
    }

    // @@protoc_insertion_point(class_scope:SearchFileResponse)
    private static final SearchFileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SearchFileResponse();
    }

    public static SearchFileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchFileResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchFileResponse>() {
      @Override
      public SearchFileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchFileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchFileResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SearchFileResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public SearchFileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchFileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchFileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchFileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021search_file.proto\032\014common.proto\"?\n\021Sea" +
      "rchFileRequest\022\016\n\006nodeId\030\001 \003(\003\022\032\n\007baseRe" +
      "q\030\377\001 \001(\0132\010.BaseReq\"K\n\022SearchFileResponse" +
      "\022\027\n\010nodeList\030\001 \003(\0132\005.Node\022\034\n\010baseResp\030\377\001" +
      " \001(\0132\t.BaseRespB1\n\031com.graduate.design.p" +
      "rotoB\nSearchFileZ\010./pb_genb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.getDescriptor(),
        });
    internal_static_SearchFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchFileRequest_descriptor,
        new String[] { "NodeId", "BaseReq", });
    internal_static_SearchFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SearchFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchFileResponse_descriptor,
        new String[] { "NodeList", "BaseResp", });
    Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
